# .streamlit/secrets.toml

[trino]
host = "trino.dev.music-flo.io"
port = 8889
user = "shen"

aws_access_key_id = "AKIA6E24WOP27I6N3UXP"
aws_secret_access_key = "YOUR_AWS_SECRET_ACCESS_KEY"
# region_name = "ap-northeast-2" # 필요 시 AWS 리전 설정
